#! /bin/bash

for file in $(git diff --staged --name-only --diff-filter=AR | grep "^\..*")
do
    grep -xq $file list || (echo "ERROR: add dotfiles to list before commit" >&2 && exit 1)
done

[ -f Brewfile ] && mv -f Brewfile Brewfile.bak
brew bundle dump
diff Brewfile Brewfile.bak && rm -f Brewfile.bak
