name: benchmark

on:
  push:
    branches:
      - master

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install zsh for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install zsh
      - name: Install zsh for macOS
        if: matrix.os == 'macos-latest'
        run: brew install zsh
      
      - name: Set cache path to env
        run: |
          echo "brew-opt=$(brew --prefix)/opt" >> $GITHUB_ENV
          echo "brew-cellar=$(brew --cellar)" >> $GITHUB_ENV
      - name: Cache development dependencies
        uses: actions/cache@v2
        with: 
          path: |
            ~/.pyenv
            ~/.n
            ${{ env.brew-opt }}
            ${{ env.brew-cellar }}
          key: ${{ runner.os }}-cache

      - name: Initialize zsh
        run: zsh ./init.zsh

      - name: Install hyperfine
        run: brew install hyperfine
      - name: Benchmark
        run: | 
          hyperfine --show-output --warmup 3 'zsh -i -c exit' -n "zsh load time $RUNNER_OS" --export-json result.json
          jq '.results[] | .["name"] = .command | .["unit"] = "millisecond" | .["value"] = (.mean * 1000 | tostring) | [{name, unit, value}]' result.json > bench.json
      - name: Store bench
        uses: benchmark-action/github-action-benchmark@v1.10.0
        with:
          tool: "customSmallerIsBetter"
          output-file-path: bench.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: 150%
          alert-comment-cc-users: '@rajyan'
     
