name: benchmark

on:
  push:
    branches:
      - master

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Test installation in Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install zsh
        run: sudo apt-get update && sudo apt-get install -y zsh
      - name: init zsh
        run: zsh ./init.zsh
        env:
          DOTSDIR: /home/runner/work/dotfiles/dotfiles/dots
      - name: benchmark
        run: | 
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_amd64.deb
          sudo dpkg -i hyperfine_1.12.0_amd64.deb
          hyperfine --show-output --warmup 3 'zsh -i -c exit' -n 'zsh load time' --export-json result.json
          jq '.results[] | .["name"] = .command | .["unit"] = "millisecond" | .["value"] = (.mean * 1000 | tostring) | [{name, unit, value}]' result.json > bench.json
      - name: store bench
        uses: benchmark-action/github-action-benchmark@v1.10.0
        with:
          tool: "customSmallerIsBetter"
          output-file-path: bench.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: 130%
          alert-comment-cc-users: '@rajyan'
     
